### PR TITLE
Add Captions to Images

### PR DESCRIPTION
**Pull request by pfandzelter**
As described in [this blog post](https://sebastiandedeyne.com/captioned-images-with-markdown-render-hooks-in-hugo/) it's fairly easy to add images captions in hugo. This adds that feature to smol without impacting existing articles.

### CODE REVIEW

**Comment by colorchestra** [comment]
Hey @pfandzelter, thanks for your PR! This looks like a fantastic feature to have. However, I can't get it to work - I can embed an image with a title and it correctly outputs HTML with the corresponding title tag, but the image caption doesn't actually show up in the browser. Do you have an idea why that might be? I assume it works on your end? 
I'm testing this using Hugo v0.78 extended on Fedora Linux.

**Comment by pfandzelter** [comment]
Thanks @colorchestra, I checked again and it seems that I needed to move the `render-image.html` to a `_markup` folder. I tried it with a new blog and it worked great now.

**Comment by colorchestra** [comment]
Hey @pfandzelter, thanks, the captions look great! However, I am now a bit unhappy about the fact that images with captions (or "figures") are displayed smaller than images without captions. Sorry for being this nitpicky, but could you help me fix this?

Adding the following lines to an article in my blog yields the result in the attached screenshot.

```
![Screenshot vom rpm-ostree Befehl](/static/fedora-silverblue-ostree.png)

![Screenshot vom rpm-ostree Befehl](/static/fedora-silverblue-ostree.png "The same image as above, but with a caption")
```

Screenshot_2020-11-18 Distrowars 2020 Fedora Silverblue

Thank you!

**Comment by colorchestra** [comment]
Actually, that seems to be a feature (?) of the HTML figure tag. Putting just these few lines into an HTML file (without CSS) gives me a similar result (the 'figure' is indented by a bit). I'll do some more research...

**Comment by pfandzelter** [comment]
Hm yes, that appears to be caused by the use of the `<figure>` tag. We could also wrap the image without caption in a `<figure>` tag to make it consistent. Would you prefer both to be smaller or both to be larger?

**Comment by colorchestra** [comment]
I'd prefer them to be larger. It seems to work with inline css when using figures, like so: `<figure style="margin:0">` 

But I'd like to avoid inline css and put it in style.css. Adding `figure {margin:0}` there doesn't seem to have an effect, I'm not sure how to do it correctly.

**Comment by pfandzelter** [comment]
Ok, I wrapped the lone image in a figure tag as well (so if required, all image-related CSS can be customized consistently) and added `figure: {margin: auto}`, which worked for me.

In my Chrome I sometimes need to invalidate the cache with `cmd/cntrl + shift + R` to view the most recent CSS file, maybe that's why you didn't see the changes when changing it

**Comment by colorchestra** [comment]
That's perfect! And indeed, using "Disable cache" did the trick - TIL. 

Merging this. Have a good evening!

**Pull request merged**
